CREATE DATABASE Bernhardt;

USE Bernhardt;

CREATE TABLE EMPLOYEE (
    EMPNO INT(4),
    ENAME VARCHAR(20),
    DESIGNATION VARCHAR(25),
    HIREDATE DATE,
    SALARY INT(10),
    COMM DECIMAL(10,2),
    DEPTNO INT(4)
);

DESC EMPLOYEE;

INSERT INTO EMPLOYEE
VALUES
(1011,'Ram','Manager','1995-01-01',20000,800,100),
(1021,'Hari','Accountant','1999-04-04',15000,650,200),
(1456,'Shyam','Clerk','1995-07-03',12000,500,300),
(1045,'Sita','Analyst','1998-10-06',18000,700,400),
(1099,'Ramesh','Clerk','1996-01-01',10000,400,300),
(1060,'Hari','Clerk','1997-10-25',10000,400,300);

SELECT * FROM EMPLOYEE;

SELECT ENAME, DESIGNATION, SALARY
FROM EMPLOYEE;

SELECT ENAME
FROM EMPLOYEE
WHERE DESIGNATION='Clerk';

SELECT *
FROM EMPLOYEE
WHERE DESIGNATION='Clerk'
AND DEPTNO=300;

SELECT ENAME, EMPNO, DESIGNATION
FROM EMPLOYEE
WHERE DESIGNATION IN ('Manager','Analyst');

SELECT *
FROM EMPLOYEE
WHERE DESIGNATION NOT IN ('Director','Receptionist');

SELECT *
FROM EMPLOYEE
WHERE DESIGNATION IN ('Director','Receptionist');

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 12000 AND 20000;

SELECT ENAME, SALARY
FROM EMPLOYEE
WHERE SALARY<10000
OR SALARY>15000;

SELECT DISTINCT DESIGNATION
FROM EMPLOYEE;

SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'R%';

SELECT EMPNO, ENAME
FROM EMPLOYEE
WHERE ENAME LIKE '%m';

SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'H%i';

SELECT EMPNO, ENAME
FROM EMPLOYEE
WHERE ENAME LIKE 'R__';

SELECT ENAME
FROM EMPLOYEE
ORDER BY ENAME ASC;

SELECT ENAME
FROM EMPLOYEE
ORDER BY ENAME DESC;

SELECT ENAME, SALARY, SALARY*1.20 AS INCREASED_SALARY
FROM EMPLOYEE;

SELECT ENAME, COMM, COMM*1.20 AS INCREASED_COMM
FROM EMPLOYEE;

SELECT ENAME, SALARY+COMM AS TOTAL_SALARY
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE DESIGNATION='Manager'
OR SALARY>12000;

SELECT SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE;

SELECT COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE;

SELECT COUNT(DISTINCT DEPTNO) AS TOTAL_DEPARTMENTS
FROM EMPLOYEE;

SELECT DEPTNO, MAX(SALARY) AS MAX_SALARY
FROM EMPLOYEE
GROUP BY DEPTNO;

SELECT *
FROM EMPLOYEE
WHERE SALARY=(SELECT MAX(SALARY) FROM EMPLOYEE);

SELECT DISTINCT DEPTNO
FROM EMPLOYEE
WHERE SALARY>(SELECT AVG(SALARY) FROM EMPLOYEE);

SELECT DISTINCT DEPTNO
FROM EMPLOYEE
WHERE SALARY>12000;

ALTER TABLE EMPLOYEE
DROP COLUMN COMM;

ALTER TABLE EMPLOYEE
RENAME COLUMN DEPTNO TO DPNO;

ALTER TABLE EMPLOYEE
ADD PHONE BIGINT;

ALTER TABLE EMPLOYEE
MODIFY EMPNO VARCHAR(5);

DROP TABLE EMPLOYEE;

DROP DATABASE Bernhardt;